steps:
  - name : 'gcr.io/cloud-builders/docker'
    args : ['build', '-t', 'us-central1-docker.pkg.dev/modern-ellipse-449011-s1/demo-docker/dummy-image', "."]
    id : 'Build Docker Image'

  - name : 'gcr.io/cloud-builders/docker'
    args : ['push', 'us-central1-docker.pkg.dev/modern-ellipse-449011-s1/demo-docker/dummy-image']
    id : 'Push Docker Image'

  - name : 'google/cloud-sdk:latest'
    entrypoint : 'sh'
    args :
      - -xe
      - -c
      - |
        gcloud deploy apply --file devcluster.yaml --region=us-central1
        gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gkecicd-pipelines --region=us-central1 --from-k8s-manifest=./kubernetes/app.yaml
options:
  logging: CLOUD_LOGGING_ONLY
