apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gkecicd-pipelines
description: main application piepline
serialPipeline:
  stages:
    - targetId: dev
      profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: dev GKE cluster
gke:
  cluster: projects/demo/locations/us-central1/clusters/demo-cluster-1