appVersion: apps/v1
kind: Deployment
metadata:
  name: gcpk-service
spec:
  replicas: 3
  selector:
    matchLabels:
      run: gcpk-service
    template:
      metadata:
        labels:
          run: gcpk-service
      spec:
        containers:
          - name: gcpk-service
            image: us.gcr.io/demo/docker/gcpcloud:v1
            ports:
              - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: gcpk-service
  labels:
    run: gcpk-service
spec:
  selector:
    run: gcpk-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer